server:
  port: 8101
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:8001/eureka/,http://replica2:8002/eureka/,http://replica3:8003/eureka/ #同时注册到两个注册中心