server:
  port: 8003
spring:
  application:
    name: eureka-server-8003
eureka:
  instance:
    hostname: replica3
  client:
    serviceUrl:
      defaultZone: http://replica1:8001/eureka/,http://replica2:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true