server:
  port: 8002
spring:
  application:
    name: eureka-server-8002
eureka:
  instance:
    hostname: replica2
  client:
    serviceUrl:
      defaultZone: http://replica1:8001/eureka/,http://replica3:8003/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true